language: ruby

rvm:
  - 2.5.7

install:
  - gem uninstall bundler
  - gem install bundler --version '2.1.4'
  - bundle install

sudo: false

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: jruby-head

gemfile:
  - gemfiles/rails_6.gemfile

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - simon@rentzke.com
    on_success: 'never'
    on_failure: 'change'
